[profile.default]
src = "src"
out = "out"
libs = ["lib"]
auto_detect_remappings = true

fs_permissions = [
    { access = "read", path = "./script/addresses.json" },
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]
remappings = [
    "forge-std/=./lib/forge-std/src/",
    "foundry-devops/=./lib/foundry-devops/src/",
    "@openzeppelincontracts/contracts/=./lib/openzeppelin-contracts/contracts",
]
[fuzz]
runs = 1000
seed = '0x2'


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
